# Generated by Django 5.2.5 on 2025-08-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleaddress',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='MultipleAddress',
        ),
    ]
