# Generated by Django 5.2.5 on 2025-08-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_multipleaddress_customer_delete_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
#