# Use root/example as user/password credentials

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MysqlRo0tP@ssw0rd1234
      MYSQL_USER: django
      MYSQL_PASSWORD: MysqlDj@ang0P@ssw0rd1234
      MYSQL_DATABASE: django-learning
    # (this is just an example, not intended to be a production configuration)
