services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: P0stgErsp@sSw0rd1234
      POSTGRES_USER: django
      POSTGRES_DB: django-learning
